spring :
  datasource:
    username: root
    password: antonin
    url: jdbc:mariadb://localhost:3306/serverdb
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB10Dialect